### ISSUE TITLE
Array as input process

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#61]
@Test
    void testArrayInput(){
        def process = processFactory.create(
                "title",
                [inputA : ['st_area', 'st_type', 'st_perimeter']],
                [outputA : String],
                { inputA ->[outputA :  inputA[0]+'the_geom) as area']}
        )
    }

@j3r3m1

**Comment by j3r3m1** [comment]
What if we want functions such as "st_buffer" that needs arguments ? Should we add ['st_area', 'st_type', 'st_perimeter', ['st_buffer', 100]] or it is not designed for this purpose ?

**Comment by ebocher** [comment]
it is not designed for this purpose.

**Comment by SPalominos** [comment]
In the process declaration, for the inputs and outputs, the pattern is `[inputA : type, inputB, type, ...]`.
In the case of the example : 
``` groovy
@Test
    void testArrayInput(){
        def process = processFactory.create(
                "title",
                [inputA : String[]],
                [outputA : String],
                { inputA ->[outputA :  inputA[0]+'the_geom) as area']}
        )
    }
```

**Comment by j3r3m1** [comment]
That is right.
However, I still do not see whether or not a Table should be passed as input. In the case this is not the case, it means that another process should execute the sql query from an input table ?
Anyway, in the script presented here, we must at least loop on the list[] and give a "correct" name to the field that will be created in the future ?

``` groovy
@Test
    void testArrayInput(){
        def process = processFactory.create(
                "title",
                [inputA : String[]],
                [outputA : String],
                { inputA ->
                concat = ""
                for (fct in inputA){   
                    concat += '$fct(the_geom) as ${fct[3..-1]},'
                }
                [outputA : concat[0..-2]}
        )
    }
```

**Comment by SPalominos** [comment]
You can pass an ITable as a process input, but you should no call getJdbcDataSource on it (this possibility will be removed soon). If you want to do so, you should pass the JdbcDataSource (H2GIS or POSTGIS object as example).

For your example, you just have a problem of quoting, instead of `concat += '$fct(the_geom) as ${fct[3..-1]},'` you should write `concat += "$fct(the_geom) as ${fct[3..-1]},"` (double quote instead of simple quote). The `${myVar[i]}` syntax works only inside double quote. 
This test works well with simple array as input (like `['st_area', 'st_type', 'st_perimeter']`.
To be able to use input like `['st_area', 'st_type', 'st_perimeter', ['st_buffer', 100]]` you should write something like :
``` java
for (fct in inputA){
    concat += fct instanceof List ?
            "${fct[0]}(the_geom, ${fct[1]}) as ${fct[0][3..-1]}," :
            "$fct(the_geom) as ${fct[3..-1]},"
}
```
that will give you as output `"st_area(the_geom) as area,st_type(the_geom) as type,st_perimeter(the_geom) as perimeter,st_buffer(the_geom, 100) as buffer"`

**Comment by SPalominos** [comment]
@ebocher Is this issue still open ?

**Comment by ebocher** [comment]
nop thx
