### ISSUE TITLE
Log process name

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisdata#89]
It would be nice if we could automatically log the name of the process that is executed

**Comment by SPalominos** [comment]
Yes it would be great to log processes start and end, but I'm not in favour to log it in the info output. I think it will be better to use the debug ouput. What do you think about ?

**Comment by j3r3m1** [comment]
What do you mean by debug output ? We would need to add a log in each of the process definition ?

**Comment by SPalominos** [comment]
The logger have different channels : error, warn, info, debug. Logging the process executed into 'debug' allow to hide it on normal execution to avoid to give too much information to a standard user, but on test it will be displayed in order to give to advanced user all the information about test running.
